version: '3.10'

services:
  web:
    build: .
    container_name: python-platform-web
    restart: unless-stopped
    ports:
      - "5000:5000"  # Flask uygulaması
      - "7923:7923"  # FastAPI
    volumes:
      - .:/code
      - notebooks:/code/notebooks_repo
    environment:
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://pythonplayground:pythonplayground@mariadb.verira.internal/python_platform
      - PYTHONUNBUFFERED=1
      - FASTAPI_DOMAIN=http://0.0.0.0
      - PYTHONPATH=/code
    working_dir: /code
    command: python app.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  notebooks:
    driver: local