version: '3.10'

services:
  web:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    container_name: python-platform-web
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "7923:7923"
    volumes:
      - notebooks_repo:/code/notebooks_repo
    environment:
      - FLASK_APP=app.py
      - SECRET_KEY=dev-key
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://pythonplayground:pythonplayground@10.0.50.20/python_platform
      - PYTHONUNBUFFERED=1
      - FASTAPI_DOMAIN=http://127.0.0.1
      - PYTHONPATH=/code
    working_dir: /code
    command: >
      bash -c '
      if [ -d .git ]; then 
        git rev-parse HEAD > .git_commit 
      elif [ -d /code/.git ]; then 
        git -C /code rev-parse HEAD > .git_commit 
      else 
        echo "$(date): Git repo bulunamadı" > .git_commit
      fi && 
      python app.py'
    network_mode: "host"

volumes:
  notebooks_repo: