version: '3.10'

services:
  web:
    build: .
    container_name: python-platform-web
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "7923:7923"
    volumes:
      - .:/code
      - notebooks:/code/notebooks_repo
    environment:
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://pythonplayground:pythonplayground@mariadb.verira.internal/python_platform
      - PYTHONUNBUFFERED=1
      - FASTAPI_DOMAIN=http://0.0.0.0
      - PYTHONPATH=/code
    working_dir: /code
    command: python app.py
    extra_hosts:
      - "mariadb.verira.internal:host-gateway"

volumes:
  notebooks:
    driver: local