version: '3.10'

services:
  web:
    build: .
    container_name: python-platform-web
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "7923:7923"
    volumes:
      - .:/code
      - notebooks:/code/notebooks_repo
    environment:
      - FLASK_APP=app.py
      # IP adresini MySQL sunucunuzun gerçek IP adresiyle değiştirin
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://pythonplayground:pythonplayground@10.0.50.20/python_platform
      - PYTHONUNBUFFERED=1
      - FASTAPI_DOMAIN=http://localhost
      - PYTHONPATH=/code
    working_dir: /code
    command: python app.py
    network_mode: "host"  # Host ağını kullanarak dış veritabanına erişim

volumes:
  notebooks:
    driver: local