version: '3.10'

services:
  web:
    build:
      context: .
    container_name: python-platform-web
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - notebooks_repo:/code/notebooks_repo
    environment:
      - FLASK_APP=app.py
      - SECRET_KEY=dev-key
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://pythonplayground:pythonplayground@10.0.50.20/python_platform
      - PYTHONUNBUFFERED=1
      - FASTAPI_DOMAIN=http://127.0.0.1
      - WEB_PORT=5000
      - PYTHONPATH=/code
      - GIT_COMMIT=${SOURCE_COMMIT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python-app.rule=Host(`python.batuhanacikgoz.com.tr`)"
      - "traefik.http.routers.python-app.entrypoints=https"
      - "traefik.http.routers.python-app.tls=true"
      - "traefik.http.routers.python-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.python-app.loadbalancer.server.port=5000"
      - "coolify.managed=true"
    working_dir: /code
    command: python app.py
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  notebooks_repo: